config/routes.rb
Rails.application.routes.draw do
  resources :relationships,       only: [:create, :destroy]
  resources :carts
  resources :orders
  resources :ratings
  resources :products
  resources :profiles
  resources :charges
  get 'contact' => 'static_pages#contact'
  get 'home/index'
  root 'home#index'
   devise_for :users

  resources :users do
    member do
      get :following, :followers
    end
  end

  # get 'users/sign_up'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user, optional: true
  has_many :ratings, dependent: :destroy
  has_many :product_orders
  has_many :orders, through: :product_orders
  accepts_nested_attributes_for :product_orders, allow_destroy: true
end

# has_many :user_projects
#   has_many :projects, through: :user_projects

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :new ]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json

  def show
    @product = Product.includes(:user).find(params[:id])
    @ratings = @product.ratings.includes(:user).all
    @rating  = @product.ratings.build(user_id: current_user.id) if current_user
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit

  # POST /products
  # POST /products.json

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
        flash[:success] = 'Product added!'
        redirect_to products_path
    else
        render 'new'
    end
end

  def edit
      @product = Product.find(params[:id])
  end
  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json

  def update
      @product = Product.find(params[:id])
      if @product.update_attributes(product_params)
        flash[:success] = 'Product edited!'
        redirect_to products_path
      else
        render 'edit'
      end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:image,:user_id, :title, :kind, :size, :price, :description, :image_data)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="container">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="container">
  <%= form.hidden_field :user_id %>


  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :product_title %>
  </div>

  <div class="field">
    <%= form.label :type %>
    <%= form.select :kind, [["wall sticker", "wall_sticker"], ["umbrella", "umbrella"], ["nail","nail"], ["laptop","laptop"], ["tattoo sticker","tattoo sticker"]], {prompt: "Select the type "} %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size, id: :product_size %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description %>
  </div>

  <div class="field">
      <%= form.label :image %>
      <%= form.hidden_field :image, value: @product.cached_image_data if defined?(@product.cached_image_data) %>
      <%= form.file_field :image %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
<h1>Products</h1>
<% @products.each do |product| %>
  <img class="" src="<%= product.image_url %>" alt="Card image cap" width="320" height="320">

<tr>
  <td><%= link_to 'Show', product %></td>
  <td><%= link_to 'Edit', edit_product_path(product) %></td>
  <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>
<% end %>
</br></br>

<%= link_to 'New Product', new_product_path %>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <p>
    <strong>User:</strong>
    <%= @product.user.id %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= @product.title %>
  </p>

  <p>
    <strong>Type:</strong>
    <%= @product.kind %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= @product.size %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= @product.price %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= @product.description %>
  </p>

  <p>
    <strong>Image data:</strong>
    <td><img src= "<%= @product.image_url %>" height="400"></td>
  </p>

  <!-- orders_products -->

  <% if current_user.order.present? %>
  <%= link_to 'Create cart and add to cart', orders_path(order: {product_id: @product.id}), method: :post %>
  <% else %>
  <%= link_to 'Add to existing cart', order_path(current_user.order.id, order: {product_id: @product.id}), method: :put %>
  <% end %>
  <br /><br /><br /><br />

  <% @ratings.each do |rating| %>
  <strong><%= rating.user.email %></strong>
  <br />
  <% rating.rating.to_i.times do %>
  <span class = "star">★</span>
  <% end %>


  <p><%= rating.comment %></p>
  <% if user_signed_in? && rating.user == current_user %>
  <p><%= link_to 'Delete', rating_path(rating), method: :delete %></p>
  <% end %>
  <% end %>
  <% if user_signed_in? %>
  <br /><br />
  <%= render 'ratings/form' %>
  <% end %>
</div>



<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>


<%= link_to 'New Rating', new_rating_path %>

</div>